apiVersion: 1.0.0
kind: Plugin
metadata:
  name: Amazon S3 Storage
  description: S3 Storage Plugin for Reekoh IoT Platform. Stores your device data to Amazon S3.
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Storage
  price: 0
  tags:
    - storage
    - amazon
    - s3
    
  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    documentation: README.md
    config:
      key:
        label: Access Key ID
        type: String
        required: true
        help: "Specify your AWS Access Key ID."
        maxLength: 1000
      secret:
        label: Secret Access Key
        type: Password
        required: true
        help: "Specify your AWS Secret Access Key."
        maxLength: 1000
      bucker:
        label: Bucker
        type: String
        required: true
        help: "Specify your AWS S3 Bucket."
        maxLength: 1000
      region:
        label: Region
        type: String
        required: false
        maxLength: 1000
        enum:
          - us-standard
          - us-west-2
          - us-west-1
          - eu-west-1
          - ap-southeast-1
          - ap-northeast-1
          - sa-east-1
        default: us-standard
        help: "(Optional) Specify your AWS S3 Region. Default us-standard."
      path:
        label: Path
        type: String
        required: false
        help: "(Optional) Specify your AWS Bucket root folder. Default root (/)."
        maxLength: 1000
      fileNameKey:
        label: File Name Key
        type: String
        required: false
        help: "(Optional) If blank, file names will be auto-generated otherwise, the value of this field is grabbed from the data and set as name of the file."
        maxLength: 1000
      fileContentKey:
        label: File Content Key
        type: String
        required: false
        help: "(Optional) If blank, the content of the file is the data itself (JSON Document) otherwise, the value of this field is grabbed from the data and set as contents of the file."
        maxLength: 1000
